# Generated by Django 6.0.2 on 2026-02-18 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_request_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
