# Generated by Django 6.0.2 on 2026-02-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_friend_request_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='friend_request_token',
        ),
    ]
